spring:
  datasource:
    url: jdbc:oracle:thin:@10.224.201.59:1521:orcl
    username: zqinfo
    password: 181818
    driverClassName:  oracle.jdbc.driver.OracleDriver
    validationQuery: select * from dual
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: fcsc_redis
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.example.model
security:
  basic:
    enabled: false
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
